openai:
  OPENAI_API_KEY: ''
  OPENAI_API_BASE: ''
  OPENAI_ORGANIZATION: ''

azure:
  AZURE_OPENAI_API_KEY: ''
  AZURE_OPENAI_ENDPOINT: ''
  OPENAI_API_VERSION: ''

google:
  GOOGLE_API_KEY: ''

anthropic_vertex: # gcloud auth application-default login
  PROJECT_ID: ''
  REGION: ''

anthropic:
  ANTHROPIC_KEY : ''

nvidia:
  NVIDIA_API_KEY: ''